### ISSUE TITLE
The unload button does not appear in inventory when Combat Extended is installed.

### ISSUE THREAD

**Issue by Taranchuk** [catgirlfighter/RimWorld_CommonSense#12]
I tried to rearrange the mods in places, it does not help. The button appears if I remove CE from the modlist. Hugslib log (no red errors though):  
https://gist.github.com/HugsLibRecordKeeper/5a33a23233c3eb385977e76dab095ddb

**Comment by catgirlfighter** [comment]
Probably CE just overrides inventory UI instead of adding their stuff. I'll... try to check it? I'm not quite in an active modding mode currently :|

**Comment by catgirlfighter** [comment]
Sorry, CE is outside of my field of operations.
