### ISSUE TITLE
Hello brake incompatabiliti with pickup and haul mod(

### ISSUE THREAD

**Issue by Zaazik** [catgirlfighter/RimWorld_CommonSense#16]
That mod https://github.com/Mehni/PickUpAndHaul
You has conflickt when turn on options Settings.adv_haul_all_ings
Can you plz fix it(
What happen when both mod work.
Pawn take order to make some items in table, afeter thay take order haul items to invenroy and go tryin find another items for more hauling, and its can go to loop and pawn will make it all day, and not craft any items ( If you can tell me how i can solve that i will try solve that inside on mod via merge request in PickUpAndHaul, or you will make some little patch for this mod. PLZ help( 
Sorry for my bad eng(

**Comment by Mehni** [comment]
possibly already fixed on PU&H side.

https://github.com/Mehni/PickUpAndHaul/pull/37

**Comment by catgirlfighter** [comment]
Yeah, sorry I'm that slow to react on github.
