### ISSUE TITLE
Wrong or missing application of drug policies.

### ISSUE THREAD

**Issue by jinks** [catgirlfighter/RimWorld_CommonSense#31]
Re-post from the issue thread on Steam:

The application of drug policies for bringing joy-food and social drugs to sick patients seems to not work correctly.

I had a chemical interest pawn on addiction detox with no drugs allowed, but my doctors kept feeding him all manner of drugs (Wake-Up, Flake, mod teas) and I couldn't for the life of me figure out why. - Some of those drugs are forbidden in every policy I have.

I'm not sure if they apply their own policy or the patients for bringing this stuff, or even if his chemical fascination overrides the check, but turning the option off fixed the issue.

Some discussion and screenshots here: https://www.reddit.com/r/RimWorld/comments/p6ed2i/why_do_my_pawns_feed_all_manner_of_drugs_to_my/

**Comment by catgirlfighter** [comment]
Made a fix with 1.1.43, should be alright now.
