### ISSUE TITLE
Conflict with PickUpAndHault

### ISSUE THREAD

**Issue by uzver91** [catgirlfighter/RimWorld_CommonSense#33]
Hello.
When PUAH unloading hauled items from inventory (second, third items, etc), interrupded pawn put item back to inventory and forget about it.
Disabling PutBackToBackpack didn't affect, I found issue in PCT module (bool SneakyMoveToInventory). Disabling it get things normally.
Please, add option to disable PCT module with (or without) PutBackToBackpack feature in cfg.

**Comment by catgirlfighter** [comment]
Disabling an option doesn't work because it's not even used. I guess a flag got lost after some fix. Fixed it.

**Comment by uzver91** [comment]
That was quick. Many thanks!
