### ISSUE TITLE
Apologies, not sure where else to put this that isn't steam.

### ISSUE THREAD

**Issue by Trisscar05** [catgirlfighter/RimWorld_CommonSense#39]
I'm one of the Troubleshooters on the main Rimworld server, we have a few reports (that have more than just steam commenter nonsense) about things Common Sense might be doing? May I ask that you contact us please?

**Comment by catgirlfighter** [comment]
Sure. How should I contact you?

**Comment by Trisscar05** [comment]
Just join the main Rimworld server and say you made the mod mostly.

**Comment by Trisscar05** [comment]
sorry, this is specifically a discord server thing, I should have mentioned. I dunno if you want me to provide a link cause chances of scams and shizz?

**Comment by catgirlfighter** [comment]
I guess it's ludeon development server? I'll check it out later today!

**Comment by Trisscar05** [comment]
No, specifically it's the community server uno momento....
https://discord.gg/rimworld
