### ISSUE TITLE
Throwing MissingMethodException: FoodUtility.WillEat

### ISSUE THREAD

**Issue by lilwhitemouse** [catgirlfighter/RimWorld_CommonSense#41]
No idea what's going on here, but I got an exception when using your mod:
```
Exception filling tab RimWorld.ITab_Pawn_Gear: System.MissingMethodException: bool RimWorld.FoodUtility.WillEat(Verse.Pawn,Verse.Thing,Verse.Pawn,bool)
  at (wrapper dynamic-method) RimWorld.FoodUtility.RimWorld.FoodUtility.WillIngestFromInventoryNow_Patch1(Verse.Pawn,Verse.Thing)
  at (wrapper dynamic-method) RimWorld.ITab_Pawn_Gear.RimWorld.ITab_Pawn_Gear.DrawThingRow_Patch1(RimWorld.ITab_Pawn_Gear,single&,single,Verse.Thing,bool)
  at RimWorld.ITab_Pawn_Gear.FillTab () [0x00357] in <4b0e501518c44dd29e11fabe5e13ce53>:0 
  at Verse.InspectTabBase+<>c__DisplayClass16_0.<DoTabGUI>b__0 () [0x00039] in <4b0e501518c44dd29e11fabe5e13ce53>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.Log:ErrorOnce (string,int)
Verse.InspectTabBase/<>c__DisplayClass16_0:<DoTabGUI>b__0 ()
Verse.ImmediateWindow:DoWindowContents (UnityEngine.Rect)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)
```
The only patch around there is:

https://github.com/catgirlfighter/RimWorld_CommonSense/blob/4b37642130bdcf6d431b0a1bcee77a83029a967e/Source/CommonSense12/CommonSense/TakeAnyDrugs.cs#L19

Any ideas?  It may not be a Common Sense bug, but it's easily reproducible for me, and it goes away if I disable CommonSense? Is it possible the .dll is built in a weird way?

**Comment by catgirlfighter** [comment]
You're playing on unstable. Unstable is incompatible with stable version of the mod, and vice versa. Can't fix that without breaking another. You can recompile a mod for unstable or just wait for it to be rolled out into stable.

**Comment by lilwhitemouse** [comment]
Never mind, it seems a developer changed a method signature, and that's what was going on!

**Comment by lilwhitemouse** [comment]
They are apparently going to fix it for the next update, so no worries :)

**Comment by lilwhitemouse** [comment]
(apologies for the unnecessary issue!)
