### ISSUE TITLE
common sense mod for 1.3

### ISSUE THREAD

**Issue by greengoseven** [catgirlfighter/RimWorld_CommonSense#46]
well, call me a maroon, but how do i get the mod? all i see are a list of html files, and a few other directories that i have no idea what to do with. I found nowhere to contact you privately, either.

**Comment by catgirlfighter** [comment]
You jus download latest, and whatever is left for 1.3 already included.

**Comment by greengoseven** [comment]
download it HOW? I clicked on files and don't se anything but what i said.

**Comment by catgirlfighter** [comment]
Code -> download ZIP.

**Comment by greengoseven** [comment]
aha! scrolled down far enough to find that instruction. should be at teh top. never would have guessed or seen it. sheesh talk about obscure. lol not YOUR fault, tho.
