### ISSUE TITLE
"Pawns will meditate only as much as they need" always enabled

### ISSUE THREAD

**Issue by fyaunen** [catgirlfighter/RimWorld_CommonSense#47]
Changing this setting in the mod options doesn't seem to do anything. I had a look at the source and I can't find any references to the variable "meditation_economy" or any related variable outside of settings.cs

**Comment by catgirlfighter** [comment]
True. My fault.

**Comment by fyaunen** [comment]
happens to the best of us :) made a PR but I dunno if there's a better way to do it, first time messing with Harmony
