### ISSUE TITLE
Null reference exception breaking bill options display

### ISSUE THREAD

**Issue by Thorbane** [catgirlfighter/RimWorld_CommonSense#49]
For an some reason c.StuffCategories at: 
 https://github.com/catgirlfighter/RimWorld_CommonSense/blob/b68cb6cc6a4733d16375c4d9b6f6fb78ba6f4af6/Source/CommonSense14/CommonSense/TextChanges.cs#L146C1-L146C1

is sometimes null, causing a cascade of NRE errors and breaking the bill display.  Adding a c.StuffCategories != null check prevents this error from breaking the rest of the menu, though it does break the ingredients display.

**Comment by catgirlfighter** [comment]
Thanks for noticing and contributing a fix. I wish people did stuff like that more often! :)
